<a href="/courses/new">Новый курс</a>

<!-- Flash-сообщения -->
<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<?php foreach ($courses as $course): ?>
  <div>
    <?= htmlspecialchars($course['title']) ?>
  </div>
<?php endforeach ?>