<h1>Форма обновления пользователя</h1>

<!-- Flash -->
<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<form action="/users/<?= $user['id'] ?>" method="POST">
  <input type="hidden" name="_METHOD" value="PATCH">
  <div>
    <label>
        Имя
      <input type="text" name="user[name]" value="<?= htmlspecialchars($userData['name'] ?? '') ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
      <div><?= $errors['name'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
      Город
      <select name="user[city]">
          <option value="">Select</option>
        <option value="3">Москва</option>
        <option value="13">Пенза</option>
        <option value="399">Томск</option>
      </select>
    </label>
    <?php if (isset($errors['city'])): ?>
      <div><?= $errors['city'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Update">
</form>