<h1>Пользователи</h1>
<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>

<div>
<?php $userName = $_SESSION['user']['name'] ?? null;  ?>
<?= $userName ? "Привет! $userName" : '' ?>
</div>

<!-- Flash вариант 1-->
<div><?php // echo empty($flashMessages) ? '' : implode('. ', $flashMessages) ?></div>

<!-- Flash вариант 2-->
<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<?php $firstUserKey = array_key_first($users); ?>
<?php if ($firstUserKey !== null): ?>
<table sytle="border: 1px solid grey">
    <tr>
        <?php foreach($users[$firstUserKey] as $key => $value): ?>
            <td><?= $key ?></td>
        <?php endforeach; ?>
    <tr>
    <?php foreach($users as $user): ?>
        <tr>
            <?php foreach($user as $key => $value): ?>
                <?php if ($key === 'name'): ?>
                    <td><a href="/users/<?= $user['id']?>"><?= $value?></a></td>
                <?php else:?>
                    <td><?= $value?></td>
                <?php endif;?>
            <?php endforeach; ?>
        <tr>
    <?php endforeach; ?>
</table>
<?php endif;?>

<!-- Paging -->
<div>
<?php foreach($paging as $key => $value): ?>
    <a href="<?= $value ?>"> <?= $key ?> </a>
<?php endforeach; ?>
</div>
