<h1>Форма входа пользователя</h1>

<!-- BEGIN -->
<?php if ($currentUser): ?>
    <div><?= $currentUser['name'] ?></div>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<?php else: ?>
    <form action="/session" method="post">
        <input type="text" required name="user[name]" value="">
        <input type="password" required name="user[password]" value="">
        <input type="submit" value="Sign In">
    </form>
<?php endif; ?>
<!-- END -->